[package]
name = "dependaboard-restate"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
dependaboard-core = { path = "../../crates/core" }
dependaboard-github = { path = "../../crates/github" }
dependaboard-store = { path = "../../crates/store" }
futures.workspace = true
reqwest.workspace = true
restate-sdk.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
